<?php
/**
 * Front Page Template
 */
get_header();

// Get customizer values with defaults
$hero_image = get_theme_mod( 'portfolio_salma_hero_image', get_template_directory_uri() . '/images/menu.jpg' );
$skills_text = get_theme_mod( 'portfolio_salma_skills_text', "ANIMATION\nWEB DESIGN\nUI/UX\nVIDEOGRAPHY\nILLUSTRATION" );
$skills_array = array_filter( array_map( 'trim', explode( "\n", $skills_text ) ) );

// Default polygon points (absolute SVG units for viewBox 0 0 1000 600)
// Angular star-ish shape with 8 points
$default_points = '150,60 500,30 850,60 950,300 850,540 500,570 150,540 50,300';
?>

<main id="primary" class="site-main">

	<!-- Hero Section with SVG Mask -->
	<section class="hero-section">

		<!-- BOTTOM LAYER: Text (revealed through the mask hole) -->
		<div class="hero-text-layer">
			<div class="hero-skills">
				<?php foreach ( $skills_array as $skill ) : ?>
					<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
				<?php endforeach; ?>
			</div>
		</div>

		<!-- TOP LAYER: Image with SVG mask (polygon creates a hole) -->
		<div class="hero-image-layer">
			<svg
				class="hero-svg"
				viewBox="0 0 1000 600"
				preserveAspectRatio="xMidYMid slice"
				aria-hidden="true"
			>
				<defs>
					<!-- Mask: white = show image, black = hole (reveals text below) -->
					<mask id="hero-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="1000" height="600">
						<!-- White background: image visible everywhere -->
						<rect x="0" y="0" width="1000" height="600" fill="white" />
						<!-- Black polygon: creates the hole -->
						<polygon id="hero-polygon" points="<?php echo esc_attr( $default_points ); ?>" fill="black" />
					</mask>
				</defs>

				<!-- Hero image with mask applied (has a hole where polygon is) -->
				<image
					id="hero-image"
					href="<?php echo esc_url( $hero_image ); ?>"
					x="0"
					y="0"
					width="1000"
					height="600"
					preserveAspectRatio="xMidYMid slice"
					mask="url(#hero-mask)"
				/>

				<!-- Control points group (rendered on top, visible in edit mode) -->
				<g id="hero-control-points" class="control-points" aria-hidden="true">
					<!-- Points will be generated by JS -->
				</g>
			</svg>
		</div>

		<!-- Accessible text for screen readers -->
		<div class="screen-reader-text">
			<h1><?php bloginfo( 'name' ); ?> - <?php echo esc_html( implode( ', ', $skills_array ) ); ?></h1>
		</div>

	</section><!-- .hero-section -->

	<!-- Page content (if any) -->
	<?php
	while ( have_posts() ) :
		the_post();
		if ( get_the_content() ) :
			?>
			<section class="page-content-section">
				<?php the_content(); ?>
			</section>
			<?php
		endif;
	endwhile;
	?>

</main>

<?php
get_footer();
