<?php
/**
 * Front Page Template
 */
get_header();

// Get customizer values with defaults
$hero_image = get_theme_mod( 'portfolio_salma_hero_image', get_template_directory_uri() . '/images/menu.jpg' );
$skills_text = get_theme_mod( 'portfolio_salma_skills_text', "ANIMATION\nWEB DESIGN\nUI/UX\nVIDEOGRAPHY\nILLUSTRATION" );
$skills_array = array_filter( array_map( 'trim', explode( "\n", $skills_text ) ) );

// Get all hero images from the images/hero folder
$hero_images = array();
$hero_dir = get_template_directory() . '/images/hero/';
if ( is_dir( $hero_dir ) ) {
	$files = glob( $hero_dir . '*.{jpg,jpeg,png,webp}', GLOB_BRACE );
	if ( $files ) {
		sort( $files );
		foreach ( $files as $file ) {
			$hero_images[] = get_template_directory_uri() . '/images/hero/' . basename( $file );
		}
	}
}
// Fallback to single hero image if no images in folder
if ( empty( $hero_images ) ) {
	$hero_images[] = $hero_image;
}

// ==========================================================================
// DEFAULT MASK SHAPE - 12 points for morph effect (4 groups of 3)
// ==========================================================================
// This wild irregular shape morphs to a full rectangle when dragged.
// Groups: A(0,1,11), B(2,3,4), C(5,6,7), D(8,9,10)
// Keep in sync with js/hero-mask.js WIDE_START
// ==========================================================================
$default_points = '150,180 380,220 620,170 870,200 800,270 900,360 850,420 620,380 380,430 130,400 200,320 100,240';
?>

<main id="primary" class="site-main">

	<!-- Hero Section with SVG Mask -->
	<section class="hero-section">

		<!-- BOTTOM LAYER: Text (revealed through the mask hole) -->
		<div class="hero-text-layer">
			<!-- Main skills - centered -->
			<div class="hero-skills">
				<?php foreach ( $skills_array as $skill ) : ?>
					<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
				<?php endforeach; ?>

				<!-- Grey copy above - absolutely positioned -->
				<div class="hero-skills-repeat hero-skills-repeat-top" aria-hidden="true">
					<?php foreach ( $skills_array as $skill ) : ?>
						<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
					<?php endforeach; ?>
				</div>

				<!-- Grey copy below - absolutely positioned -->
				<div class="hero-skills-repeat hero-skills-repeat-bottom" aria-hidden="true">
					<?php foreach ( $skills_array as $skill ) : ?>
						<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
					<?php endforeach; ?>
				</div>
			</div>
		</div>

		<!-- TOP LAYER: Image with SVG mask (polygon creates a hole) -->
		<div class="hero-image-layer" data-hero-images='<?php echo wp_json_encode( $hero_images ); ?>'>
			<svg
				class="hero-svg"
				viewBox="0 0 1000 600"
				preserveAspectRatio="xMidYMid slice"
				aria-hidden="true"
			>
				<defs>
					<!-- Mask: white = show image, black = hole (reveals text below) -->
					<mask id="hero-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="1000" height="600">
						<!-- White background: image visible everywhere -->
						<rect x="0" y="0" width="1000" height="600" fill="white" />
						<!-- Black polygon: creates the hole -->
						<polygon id="hero-polygon" points="<?php echo esc_attr( $default_points ); ?>" fill="black" />
					</mask>
				</defs>

				<!-- Hero image with mask applied (has a hole where polygon is) -->
				<image
					id="hero-image"
					href="<?php echo esc_url( $hero_images[0] ); ?>"
					x="0"
					y="0"
					width="1000"
					height="600"
					preserveAspectRatio="xMidYMid slice"
					mask="url(#hero-mask)"
				/>

				<!-- Control points group (rendered on top, visible in edit mode) -->
				<g id="hero-control-points" class="control-points" aria-hidden="true">
					<!-- Points will be generated by JS -->
				</g>
			</svg>
		</div>

		<!-- Accessible text for screen readers -->
		<div class="screen-reader-text">
			<h1><?php bloginfo( 'name' ); ?> - <?php echo esc_html( implode( ', ', $skills_array ) ); ?></h1>
		</div>

	</section><!-- .hero-section -->

	<!-- About Section - Two Column Layout with Circle Reveal -->
	<section id="about" class="about-section">
		<!-- Yellow overlay for circle reveal animation -->
		<div class="about-reveal-overlay"></div>

		<div class="about-container">
			<!-- Left: Image -->
			<div class="about-left">
				<?php
				// Get about image from customizer
				$about_image = get_theme_mod( 'portfolio_salma_about_image', '' );
				if ( $about_image ) :
					?>
					<div class="about-image">
						<img src="<?php echo esc_url( $about_image ); ?>" alt="<?php esc_attr_e( 'Salma Lopez', 'portfolio-salma' ); ?>" />
					</div>
				<?php endif; ?>
			</div>

			<!-- Right: Heading + Text -->
			<div class="about-right">
				<h2 class="about-heading">Hello!</h2>

				<div class="about-text">
					<p>I'm Salma, a 21-year-old student pursuing a degree in Interactive Media Design. Currently, I am in my fourth year at CFP-Arts Geneva.</p>

					<p>I'm eager to expand my knowledge by diving deeper into the industry and working on personal projects. While most of my current work stems from the school curriculum, I aim to demonstrate what I've learned over the past two years through projects and collaborations with teachers who are experts in their fields.</p>

					<p>In addition to my academic work, you'll also find some of my personal projects here, including digital illustrations and videography work.</p>
				</div>
			</div>
		</div>
	</section><!-- .about-section -->

	<!-- Projects Dot Grid Section -->
	<section id="projects" class="projects-section">
		<div class="projects-container">

			<!-- Dot Grid -->
			<div class="projects-dot-grid">
				<?php
				$all_projects = new WP_Query( array(
					'post_type'      => 'project',
					'posts_per_page' => -1,
					'orderby'        => 'date',
					'order'          => 'ASC',
				) );

				if ( $all_projects->have_posts() ) :
					$project_number = 1;

					while ( $all_projects->have_posts() ) :
						$all_projects->the_post();
						$number_display = str_pad( $project_number, 2, '0', STR_PAD_LEFT );
						$thumbnail_url  = get_the_post_thumbnail_url( get_the_ID(), 'large' );
						?>
						<button type="button" class="project-dot-item"
							data-project-id="<?php echo esc_attr( get_the_ID() ); ?>"
							data-project-title="<?php echo esc_attr( get_the_title() ); ?>"
							data-project-excerpt="<?php echo esc_attr( get_the_excerpt() ); ?>"
							data-project-thumbnail="<?php echo esc_url( $thumbnail_url ); ?>"
							data-project-content="<?php echo esc_attr( wp_strip_all_tags( get_the_content() ) ); ?>"
							data-project-link="<?php echo esc_url( get_the_permalink() ); ?>">
							<!-- Number + Dot -->
							<span class="project-dot-number"><?php echo esc_html( $number_display ); ?></span>
							<span class="project-dot"></span>

							<!-- Preview card (hidden, appears on hover) -->
							<div class="project-dot-preview">
								<?php if ( has_post_thumbnail() ) : ?>
									<?php the_post_thumbnail( 'medium' ); ?>
								<?php else : ?>
									<div class="project-dot-placeholder"></div>
								<?php endif; ?>
								<?php if ( has_excerpt() ) : ?>
									<div class="project-dot-excerpt">
										<?php echo esc_html( get_the_excerpt() ); ?>
									</div>
								<?php endif; ?>
							</div>
						</button>
						<?php
						$project_number++;
					endwhile;
					wp_reset_postdata();
				else :
					?>
					<p class="no-projects">No projects yet.</p>
				<?php endif; ?>
			</div>

		</div>
	</section><!-- .projects-section -->

	<!-- Page content (if any) -->
	<?php
	while ( have_posts() ) :
		the_post();
		if ( get_the_content() ) :
			?>
			<section class="page-content-section">
				<?php the_content(); ?>
			</section>
			<?php
		endif;
	endwhile;
	?>

</main>

<!-- Project Slide-in Panel -->
<div id="project-panel" class="project-panel" aria-hidden="true">
	<div class="project-panel-overlay"></div>
	<aside class="project-panel-content">
		<button type="button" class="project-panel-close" aria-label="<?php esc_attr_e( 'Close panel', 'portfolio-salma' ); ?>">
			<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<line x1="18" y1="6" x2="6" y2="18"></line>
				<line x1="6" y1="6" x2="18" y2="18"></line>
			</svg>
		</button>

		<div class="project-panel-inner">
			<div class="project-panel-image">
				<img id="panel-image" src="" alt="" />
			</div>

			<div class="project-panel-info">
				<h2 id="panel-title" class="project-panel-title"></h2>
				<p id="panel-excerpt" class="project-panel-excerpt"></p>
				<div id="panel-content" class="project-panel-description"></div>
			</div>
		</div>
	</aside>
</div>

<?php
get_footer();
