<?php
/**
 * Front Page Template
 */
get_header();

// Get customizer values with defaults
$hero_image = get_theme_mod( 'portfolio_salma_hero_image', get_template_directory_uri() . '/images/menu.jpg' );
$skills_text = get_theme_mod( 'portfolio_salma_skills_text', "ANIMATION\nWEB DESIGN\nUI/UX\nVIDEOGRAPHY\nILLUSTRATION" );
$skills_array = array_filter( array_map( 'trim', explode( "\n", $skills_text ) ) );

// Get all hero images from the images/hero folder
$hero_images = array();
$hero_dir = get_template_directory() . '/images/hero/';
if ( is_dir( $hero_dir ) ) {
	$files = glob( $hero_dir . '*.{jpg,jpeg,png,webp}', GLOB_BRACE );
	if ( $files ) {
		sort( $files );
		foreach ( $files as $file ) {
			$hero_images[] = get_template_directory_uri() . '/images/hero/' . basename( $file );
		}
	}
}
// Fallback to single hero image if no images in folder
if ( empty( $hero_images ) ) {
	$hero_images[] = $hero_image;
}

// ==========================================================================
// DEFAULT MASK SHAPE - 12 points for morph effect (4 groups of 3)
// ==========================================================================
// This wild irregular shape morphs to a full rectangle when dragged.
// Groups: A(0,1,11), B(2,3,4), C(5,6,7), D(8,9,10)
// Keep in sync with js/hero-mask.js WIDE_START
// ==========================================================================
$default_points = '150,180 380,220 620,170 870,200 800,270 900,360 850,420 620,380 380,430 130,400 200,320 100,240';
?>

<main id="primary" class="site-main">

	<!-- Hero Section with SVG Mask -->
	<section class="hero-section">

		<!-- BOTTOM LAYER: Text (revealed through the mask hole) -->
		<div class="hero-text-layer">
			<!-- Main skills - centered -->
			<div class="hero-skills">
				<?php foreach ( $skills_array as $skill ) : ?>
					<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
				<?php endforeach; ?>

				<!-- Grey copy above - absolutely positioned -->
				<div class="hero-skills-repeat hero-skills-repeat-top" aria-hidden="true">
					<?php foreach ( $skills_array as $skill ) : ?>
						<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
					<?php endforeach; ?>
				</div>

				<!-- Grey copy below - absolutely positioned -->
				<div class="hero-skills-repeat hero-skills-repeat-bottom" aria-hidden="true">
					<?php foreach ( $skills_array as $skill ) : ?>
						<span class="hero-skill"><?php echo esc_html( $skill ); ?></span>
					<?php endforeach; ?>
				</div>
			</div>
		</div>

		<!-- TOP LAYER: Image with SVG mask (polygon creates a hole) -->
		<div class="hero-image-layer" data-hero-images='<?php echo wp_json_encode( $hero_images ); ?>'>
			<svg
				class="hero-svg"
				viewBox="0 0 1000 600"
				preserveAspectRatio="xMidYMid slice"
				aria-hidden="true"
			>
				<defs>
					<!-- Mask: white = show image, black = hole (reveals text below) -->
					<mask id="hero-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="1000" height="600">
						<!-- White background: image visible everywhere -->
						<rect x="0" y="0" width="1000" height="600" fill="white" />
						<!-- Black polygon: creates the hole -->
						<polygon id="hero-polygon" points="<?php echo esc_attr( $default_points ); ?>" fill="black" />
					</mask>
				</defs>

				<!-- Hero image with mask applied (has a hole where polygon is) -->
				<image
					id="hero-image"
					href="<?php echo esc_url( $hero_images[0] ); ?>"
					x="0"
					y="0"
					width="1000"
					height="600"
					preserveAspectRatio="xMidYMid slice"
					mask="url(#hero-mask)"
				/>

				<!-- Control points group (rendered on top, visible in edit mode) -->
				<g id="hero-control-points" class="control-points" aria-hidden="true">
					<!-- Points will be generated by JS -->
				</g>
			</svg>
		</div>

		<!-- Accessible text for screen readers -->
		<div class="screen-reader-text">
			<h1><?php bloginfo( 'name' ); ?> - <?php echo esc_html( implode( ', ', $skills_array ) ); ?></h1>
		</div>

	</section><!-- .hero-section -->

	<!-- About Section - Two Column Layout with Circle Reveal -->
	<section id="about" class="about-section">
		<!-- Yellow overlay for circle reveal animation -->
		<div class="about-reveal-overlay"></div>

		<div class="about-container">
			<!-- Left: Image -->
			<div class="about-left">
				<?php
				// Get about image from customizer
				$about_image = get_theme_mod( 'portfolio_salma_about_image', '' );
				if ( $about_image ) :
					?>
					<div class="about-image">
						<img src="<?php echo esc_url( $about_image ); ?>" alt="<?php esc_attr_e( 'Salma Lopez', 'portfolio-salma' ); ?>" />
					</div>
				<?php endif; ?>
			</div>

			<!-- Right: Heading + Text -->
			<div class="about-right">
				<h2 class="about-heading"><?php echo esc_html( get_theme_mod( 'portfolio_salma_about_heading', 'Hello!' ) ); ?></h2>

				<div class="about-text">
					<?php
					$about_text = get_theme_mod( 'portfolio_salma_about_text', "I'm Salma, a 21-year-old student pursuing a degree in Interactive Media Design. Currently, I am in my fourth year at CFP-Arts Geneva.\n\nI'm eager to expand my knowledge by diving deeper into the industry and working on personal projects. While most of my current work stems from the school curriculum, I aim to demonstrate what I've learned over the past two years through projects and collaborations with teachers who are experts in their fields.\n\nIn addition to my academic work, you'll also find some of my personal projects here, including digital illustrations and videography work." );
					// Convert double line breaks to paragraphs
					$paragraphs = preg_split( '/\n\s*\n/', $about_text );
					foreach ( $paragraphs as $paragraph ) :
						$paragraph = trim( $paragraph );
						if ( $paragraph ) :
							?>
							<p><?php echo wp_kses_post( nl2br( $paragraph ) ); ?></p>
							<?php
						endif;
					endforeach;
					?>
				</div>
			</div>
		</div>
	</section><!-- .about-section -->

	<!-- Sketchbook Section -->
	<?php
	$sketchbook_enabled = get_theme_mod( 'portfolio_salma_sketchbook_enable', false );
	if ( $sketchbook_enabled ) :
		$cover_id = get_theme_mod( 'portfolio_salma_sketchbook_cover', '' );
		$pages_ids = get_theme_mod( 'portfolio_salma_sketchbook_pages', '' );

		if ( $cover_id ) :
			$cover_url = wp_get_attachment_image_url( $cover_id, 'large' );
			$pages = array();

			if ( ! empty( $pages_ids ) ) {
				$ids_array = explode( ',', $pages_ids );
				foreach ( $ids_array as $id ) {
					$page_url = wp_get_attachment_image_url( trim( $id ), 'large' );
					if ( $page_url ) {
						$pages[] = $page_url;
					}
				}
			}

			if ( $cover_url && ! empty( $pages ) ) :
				?>
				<section class="sketchbook-section" data-component="sketchbook">
					<!-- Closed state: Cover with hover button -->
					<div class="sketchbook-cover">
						<img src="<?php echo esc_url( $cover_url ); ?>" alt="<?php esc_attr_e( 'Sketchbook Cover', 'portfolio-salma' ); ?>" class="sketchbook-cover-image">
						<div class="sketchbook-open-button">
							<span>open</span>
						</div>
						<div class="sketchbook-open-cta">open</div>
					</div>

					<!-- Open state: Pages viewer -->
					<div class="sketchbook-viewer">
						<div class="sketchbook-pages">
							<?php foreach ( $pages as $index => $page_url ) : ?>
								<div class="sketchbook-page <?php echo $index === 0 ? 'active' : ''; ?>" data-page="<?php echo esc_attr( $index ); ?>">
									<img src="<?php echo esc_url( $page_url ); ?>" alt="<?php esc_attr_e( 'Sketchbook page', 'portfolio-salma' ); ?> <?php echo esc_attr( $index + 1 ); ?>">
								</div>
							<?php endforeach; ?>
						</div>

						<!-- Page indicator -->
						<div class="sketchbook-indicator">
							<span class="current-page">1</span> / <span class="total-pages"><?php echo count( $pages ); ?></span>
						</div>
					</div>
				</section>
				<?php
			endif;
		endif;
	endif;
	?>

	<!-- Page content (if any) -->
	<?php
	while ( have_posts() ) :
		the_post();
		if ( get_the_content() ) :
			?>
			<section class="page-content-section">
				<?php the_content(); ?>
			</section>
			<?php
		endif;
	endwhile;
	?>

</main>

<?php
get_footer();
